---
title-block-style: "none"
---

# Welcome to NWSSMM

**Northwest Student Chapter of the Society for Marine Mammalogy**

Welcome to the **Northwest Student Chapter of the Society for Marine Mammalogy (NWSSMM)**! We are a community of graduate and undergraduate students primarily based in **Oregon, Washington, and British Columbia**, united by our shared interest in marine mammal science.

## Who We Are

NWSSMM connects students across the Pacific Northwest who are passionate about marine mammals. While many of our members are affiliated with academic institutions, **everyone is welcome** to participate and contribute to our community.

-   Oregon State University

-   University of Washington

-   Western Washington University

-   Simon Fraser University

-   University of British Columbia

-   University of Victoria

Our **professional sponsors** are [Dr. Andrew Trites](https://mmru.ubc.ca/personnel/trites/){target="_blank"} from the University of British Columbia and [Dr. Amy Van Cise](https://www.amyvancise.com/){target="_blank"} from the University of Washington.

## What We Do

-   **Annual Chapter Meeting**: rotating yearly across PNW institutions.

-   **Biannual Newsletter**: published in Fall and Spring.

-   **Networking & Symposia**: informal gatherings and research events.

## Stay Connected

**Join Our Listserv**: [Sign up here](https://lists.oregonstate.edu/mailman/listinfo/nwssmm){target="_blank"}

**Email Us**: [nwssmm.leaders\@gmail.com](mailto:nwssmm.leaders@gmail.com)
